feat(frontend) - Export to Podlove Publisher
bugbakery/transcribee pull request #394
Opened 2023-11-26 18:03 UTC by dnkbln

Hi,

I add a new export option. The user can export the final transcript to a Podlove Publisher instance.

2023-11-27 19:47 UTC, pajowu requested changes
Thank you so much for this PR. We're also working on adding an API that exposes the SRT/WebVTT file of a document, so maybe another option would be to wait for this API and then write an external script that syncs the two. But I'm not strictly opposed against adding this to transcribee directly

2023-11-27 21:26 UTC, pajowu commented on frontend/src/editor/export/webvtt.tsx
> +          <option value="podlove">Podlove</option>
Maybe this could be renamed to something like "Upload to Podlove Publisher"

2023-12-05 19:59 UTC, dnkbln commented
I integrate your feedback.

2023-12-10 17:30 UTC, pajowu approved these changes

2023-12-10 17:38 UTC, merged